#!/bin/bash
# imgup one-click installer
# Run: bash install.sh

set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

INSTALL_DIR="/opt/imgup"
SERVICE_FILE="/etc/systemd/system/imgup.service"

echo -e "${BOLD}"
echo "  ██╗███╗   ███╗ ██████╗ ██╗   ██╗██████╗ "
echo "  ██║████╗ ████║██╔════╝ ██║   ██║██╔══██╗"
echo "  ██║██╔████╔██║██║  ███╗██║   ██║██████╔╝"
echo "  ██║██║╚██╔╝██║██║   ██║██║   ██║██╔═══╝ "
echo "  ██║██║ ╚═╝ ██║╚██████╔╝╚██████╔╝██║     "
echo "  ╚═╝╚═╝     ╚═╝ ╚═════╝  ╚═════╝ ╚═╝     "
echo -e "${NC}"
echo -e "${CYAN}Lightweight self-hosted image upload server${NC}"
echo ""

# ─── Gather config ─────────────────────────────────────────────────────────
echo -e "${CYAN}请配置以下参数（使用默认值请直接回车）：${NC}"
echo ""

read -rp "Upload directory       [/data/images]: " UPLOAD_DIR
UPLOAD_DIR="${UPLOAD_DIR:-/data/images}"

echo -ne "Base URL ${RED}(必填)${NC} [https://images.example.com]: "
read -r BASE_URL
BASE_URL="${BASE_URL:-https://images.example.com}"
# 去掉尾部斜杠
BASE_URL="${BASE_URL%/}"
# 提取纯域名（去掉协议头）
DOMAIN="${BASE_URL#https://}"
DOMAIN="${DOMAIN#http://}"

read -rp "Port                           [8765]: " PORT
PORT="${PORT:-8765}"

TOKEN=$(openssl rand -hex 16 2>/dev/null || cat /dev/urandom | tr -dc 'a-f0-9' | head -c 32)
echo -e "Upload token ${YELLOW}(auto-generated)${NC}: ${BOLD}$TOKEN${NC}"
echo ""

# ─── Install server ─────────────────────────────────────────────────────────
echo -e "${CYAN}[1/5]${NC} Creating directories..."
mkdir -p "$INSTALL_DIR" "$UPLOAD_DIR"

echo -e "${CYAN}[2/5]${NC} Copying server.py..."
cp "$(dirname "$0")/server.py" "$INSTALL_DIR/server.py"
chmod +x "$INSTALL_DIR/server.py"

echo -e "${CYAN}[3/5]${NC} Installing systemd service..."
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=imgup - Lightweight Image Upload Server
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=$INSTALL_DIR
Environment=UPLOAD_DIR=$UPLOAD_DIR
Environment=UPLOAD_TOKEN=$TOKEN
Environment=BASE_URL=$BASE_URL
Environment=PORT=$PORT
Environment=MAX_SIZE_MB=20
ExecStart=/usr/bin/python3 $INSTALL_DIR/server.py
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now imgup.service

# ─── Configure web server ────────────────────────────────────────────────────
echo -e "${CYAN}[4/5]${NC} Configuring web server..."

CONFIGURED=false
WEBSERVER=""

# ═════════════════════════════════════════════════════════════════════════════
# 优先级 1：Caddy（默认推荐，自动 HTTPS）
# ═════════════════════════════════════════════════════════════════════════════
if command -v caddy &>/dev/null; then
    WEBSERVER="Caddy"
    # 查找 Caddyfile 目录，用于放置独立的 imgup 配置文件
    CADDYFILE=""
    for f in /etc/caddy/Caddyfile /usr/local/etc/caddy/Caddyfile ~/.config/caddy/Caddyfile; do
        [ -f "$f" ] && CADDYFILE="$f" && break
    done

    if [ -n "$CADDYFILE" ]; then
        CADDY_DIR="$(dirname "$CADDYFILE")"
        IMGUP_CADDY="$CADDY_DIR/imgup.caddy"

        # 确保主 Caddyfile 包含 import 指令（仅添加一次）
        if ! grep -q "import imgup.caddy" "$CADDYFILE" 2>/dev/null; then
            echo "" >> "$CADDYFILE"
            echo "import imgup.caddy" >> "$CADDYFILE"
        fi

        # 直接覆盖写入独立配置文件（天然支持重复执行）
        if [ -f "$IMGUP_CADDY" ]; then
            echo -e "   ${CYAN}↻ 检测到已有 imgup 配置，将覆盖更新...${NC}"
        fi

        cat > "$IMGUP_CADDY" <<EOF
# imgup - auto-generated by install.sh
$DOMAIN {
    encode gzip zstd

    # 上传接口代理到本地 Python 服务
    handle /upload {
        reverse_proxy 127.0.0.1:$PORT
    }

    # 健康检查
    handle /health {
        reverse_proxy 127.0.0.1:$PORT
    }

    # 静态文件浏览
    handle {
        root * $UPLOAD_DIR
        file_server browse
    }
}
EOF

        if caddy validate --config "$CADDYFILE" 2>/dev/null; then
            systemctl reload caddy 2>/dev/null || caddy reload --config "$CADDYFILE" 2>/dev/null
            CONFIGURED=true
            echo -e "   ${GREEN}✓ Caddy 配置已写入 $IMGUP_CADDY${NC}"
            echo -e "   ${CYAN}✓ Caddy 将自动申请 HTTPS 证书${NC}"
        else
            # 配置有误，回滚
            rm -f "$IMGUP_CADDY"
            sed -i '/^import imgup\.caddy/d' "$CADDYFILE"
            echo -e "   ${RED}✗ Caddy 配置验证失败，已回滚${NC}"
            caddy validate --config "$CADDYFILE" 2>&1 | sed 's/^/   /'
        fi
    else
        echo -e "   ${YELLOW}⚠ 检测到 Caddy 但未找到 Caddyfile${NC}"
    fi

# ═════════════════════════════════════════════════════════════════════════════
# 优先级 2：Nginx（最常见的反向代理）
# ═════════════════════════════════════════════════════════════════════════════
elif command -v nginx &>/dev/null; then
    WEBSERVER="Nginx"
    NGINX_CONF="/etc/nginx/sites-available/imgup"

    # 检查是否已有 imgup 自动生成配置，有则覆盖
    if [ -f "$NGINX_CONF" ] && grep -q "# imgup - auto-generated by install.sh" "$NGINX_CONF" 2>/dev/null; then
        echo -e "   ${CYAN}↻ 检测到已有 imgup 自动生成配置，将覆盖更新...${NC}"
        # 直接覆盖写入（cat > 覆盖模式）
        OVERWRITE=true
    elif [ -f "$NGINX_CONF" ] || grep -rl "server_name.*$DOMAIN" /etc/nginx/sites-* 2>/dev/null | grep -q .; then
        echo -e "   ${YELLOW}⚠ Nginx 中已存在 $DOMAIN 的手动配置，跳过自动写入${NC}"
        CONFIGURED=true
        OVERWRITE=false
    else
        OVERWRITE=true
    fi

    if [ "$OVERWRITE" = true ]; then
        cat > "$NGINX_CONF" <<EOF
# imgup - auto-generated by install.sh
server {
    listen 80;
    server_name $DOMAIN;

    location /upload {
        proxy_pass http://127.0.0.1:$PORT;
        client_max_body_size 20M;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        root $UPLOAD_DIR;
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
    }
}
EOF
        # 检查 sites-enabled 目录是否存在
        if [ -d /etc/nginx/sites-enabled ]; then
            ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/imgup
        fi

        if nginx -t 2>/dev/null; then
            systemctl reload nginx 2>/dev/null || nginx -s reload 2>/dev/null
            CONFIGURED=true
            echo -e "   ${GREEN}✓ Nginx 配置已写入 $NGINX_CONF${NC}"
            echo -e "   ${CYAN}提示：如需 HTTPS，请运行 certbot --nginx -d $DOMAIN${NC}"
        else
            rm -f /etc/nginx/sites-enabled/imgup "$NGINX_CONF"
            echo -e "   ${RED}✗ Nginx 配置验证失败，已回滚${NC}"
        fi
    fi

# ═════════════════════════════════════════════════════════════════════════════
# 优先级 3：Apache/httpd（企业常用）
# ═════════════════════════════════════════════════════════════════════════════
elif command -v apache2 &>/dev/null || command -v httpd &>/dev/null; then
    WEBSERVER="Apache"
    APACHE_CONF="/etc/apache2/sites-available/imgup.conf"
    [ -d /etc/httpd/conf.d ] && APACHE_CONF="/etc/httpd/conf.d/imgup.conf"

    # 检查是否已有 imgup 自动生成配置，有则覆盖
    if [ -f "$APACHE_CONF" ] && grep -q "# imgup - auto-generated by install.sh" "$APACHE_CONF" 2>/dev/null; then
        echo -e "   ${CYAN}↻ 检测到已有 imgup 自动生成配置，将覆盖更新...${NC}"
        OVERWRITE=true
    elif grep -rl "ServerName.*$DOMAIN" /etc/apache2/sites-* /etc/httpd/conf.d/ 2>/dev/null | grep -q .; then
        echo -e "   ${YELLOW}⚠ Apache 中已存在 $DOMAIN 的手动配置，跳过自动写入${NC}"
        CONFIGURED=true
        OVERWRITE=false
    else
        OVERWRITE=true
    fi

    if [ "$OVERWRITE" = true ]; then
        cat > "$APACHE_CONF" <<EOF
# imgup - auto-generated by install.sh
<VirtualHost *:80>
    ServerName $DOMAIN

    # 上传接口反向代理
    ProxyPass /upload http://127.0.0.1:$PORT/upload
    ProxyPassReverse /upload http://127.0.0.1:$PORT/upload

    # 静态文件服务
    DocumentRoot $UPLOAD_DIR
    <Directory $UPLOAD_DIR>
        Options +Indexes
        Require all granted
    </Directory>

    # 上传大小限制
    LimitRequestBody 20971520
</VirtualHost>
EOF
        # 启用必要模块
        if command -v a2enmod &>/dev/null; then
            a2enmod proxy proxy_http 2>/dev/null
            a2ensite imgup 2>/dev/null
        fi

        # 验证配置
        if apache2ctl configtest 2>/dev/null || httpd -t 2>/dev/null; then
            systemctl reload apache2 2>/dev/null || systemctl reload httpd 2>/dev/null
            CONFIGURED=true
            echo -e "   ${GREEN}✓ Apache 配置已写入 $APACHE_CONF${NC}"
            echo -e "   ${CYAN}提示：如需 HTTPS，请运行 certbot --apache -d $DOMAIN${NC}"
        else
            rm -f "$APACHE_CONF"
            echo -e "   ${RED}✗ Apache 配置验证失败，已回滚${NC}"
        fi
    fi

# ═════════════════════════════════════════════════════════════════════════════
# 优先级 4：Traefik（容器化场景）
# ═════════════════════════════════════════════════════════════════════════════
elif command -v traefik &>/dev/null || [ -f /etc/traefik/traefik.yml ]; then
    WEBSERVER="Traefik"
    echo -e "   ${CYAN}检测到 Traefik，请手动添加配置：${NC}"
    echo -e "   ${YELLOW}Traefik 通常通过标签或配置文件管理路由${NC}"

# ═════════════════════════════════════════════════════════════════════════════
# 未检测到已知的 Web 服务器
# ═════════════════════════════════════════════════════════════════════════════
else
    echo -e "   ${YELLOW}⚠ 未检测到常见 Web 服务器 (Caddy/Nginx/Apache/Traefik)${NC}"
fi

# ─── Install upload client ───────────────────────────────────────────────────
echo -e "${CYAN}[5/5]${NC} Installing upload client..."
CLIENT="$INSTALL_DIR/upload.sh"
cp "$(dirname "$0")/upload.sh" "$CLIENT"
sed -i "s|https://images.example.com/upload|$BASE_URL/upload|g" "$CLIENT"
sed -i "s|change_me_please|$TOKEN|g" "$CLIENT"
chmod +x "$CLIENT"
ln -sf "$CLIENT" /usr/local/bin/imgup

# ─── Summary ─────────────────────────────────────────────────────────────────
# 获取服务器公网 IP（用于 DNS 解析提示）
SERVER_IP=$(curl -s --max-time 3 https://api.ipify.org 2>/dev/null \
         || curl -s --max-time 3 https://ifconfig.me 2>/dev/null \
         || hostname -I 2>/dev/null | awk '{print $1}')

echo ""
echo -e "${GREEN}${BOLD}✓ imgup installed successfully!${NC}"
echo ""
echo -e "  ${BOLD}图床地址 :${NC} $BASE_URL"
echo -e "  ${YELLOW}  ➜ DNS 解析：请前往域名服务商，将 ${BOLD}$DOMAIN${NC}${YELLOW} 的 A 记录解析到本服务器 IP：${BOLD}${SERVER_IP:-<你的服务器IP>}${NC}"
echo ""
echo -e "  ${BOLD}Token    :${NC} ${BOLD}${GREEN}$TOKEN${NC}"
echo -e "  ${YELLOW}  ➜ 请妥善保存此 Token！后续需填写到本地客户端（imgup 客户端）才能上传图片${NC}"
echo ""
echo -e "  ${BOLD}端口     :${NC} $PORT"
echo -e "  ${BOLD}存储目录 :${NC} $UPLOAD_DIR"
echo -e "  ${BOLD}配置文件 :${NC} $SERVICE_FILE"
echo -e "  ${CYAN}  ↑ URL 与 Token 均保存于此文件，遗忘时可在此查看${NC}"
echo ""
echo -e "  ${CYAN}上传图片 :${NC}  imgup photo.jpg"
echo -e "  ${CYAN}服务状态 :${NC}  systemctl status imgup"
echo ""

# 如果没有自动配置 Web 服务器，打印手动配置提示
if [ "$CONFIGURED" = false ]; then
    echo -e "${YELLOW}请手动配置你的 Web 服务器，以下是各平台示例：${NC}"
    echo ""
    echo -e "  ${BOLD}Caddy (推荐，自动 HTTPS)：${NC}"
    echo "    $DOMAIN {"
    echo "      handle /upload { reverse_proxy 127.0.0.1:$PORT }"
    echo "      handle { root * $UPLOAD_DIR; file_server browse }"
    echo "    }"
    echo ""
    echo -e "  ${BOLD}Nginx：${NC}"
    echo "    server {"
    echo "      listen 80; server_name $DOMAIN;"
    echo "      location /upload { proxy_pass http://127.0.0.1:$PORT; }"
    echo "      location / { root $UPLOAD_DIR; autoindex on; }"
    echo "    }"
    echo ""
fi

# 客户端配置提示
echo -e "${CYAN}${BOLD}客户端配置（Windows / Linux / macOS）：${NC}"
echo -e "  ${BOLD}域名  :${NC} $DOMAIN"
echo -e "  ${BOLD}Token :${NC} ${GREEN}$TOKEN${NC}"
echo -e "  ${RED}⚠ 请妥善保管以上信息，不要泄露给他人${NC}"
echo ""
